name: socket_client_dart
description: Socket Client for Dart
version: 0.0.8
author: loint <loint@foodtiny.com>

environment:
sdk: '>=2.0.0-dev.23.0 <2.0.0'

dependencies:
  shadow_dom: ">=0.10.0 <0.11.0"

dev_dependencies:
  test: ^0.12.8
