name: socket_client_dart
description: Socket Client for Dart
version: 0.0.9
author: loint <loint@foodtiny.com>

environment:
sdk: '>=2.0.0'

dependencies:
  shadow_dom: ">=0.10.0 <0.11.0"

dev_dependencies:
  test: ^1.3.0
